// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Google from "expo-auth-session/providers/google";

function useIdTokenAuthRequest(idTokenAuthRequestOpts) {
  var match = Google.useIdTokenAuthRequest(idTokenAuthRequestOpts);
  return [
          Caml_option.nullable_to_opt(match[0]),
          Caml_option.nullable_to_opt(match[1]),
          match[2]
        ];
}

var Google$1 = {
  useIdTokenAuthRequest: useIdTokenAuthRequest
};

var Providers = {
  Google: Google$1
};

var AuthSession = {
  Providers: Providers
};

var WebBrowser = {};

export {
  AuthSession ,
  WebBrowser ,
  
}
/* expo-auth-session/providers/google Not a pure module */
