// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNativePaperJs from "./ReactNativePaper.js";

var make = ReactNativePaperJs.AppbarHeader;

var Header = {
  make: make
};

var make$1 = ReactNativePaperJs.AppbarContent;

var Content = {
  make: make$1
};

var Appbar = {
  Header: Header,
  Content: Content
};

export {
  Appbar ,
  
}
/* make Not a pure module */
