// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Service from "../Service.bs.js";
import * as ReactNative from "react-native";
import * as Auth from "firebase/auth";

function HomeScreen(Props) {
  return React.createElement(ReactNative.View, {
              style: {
                backgroundColor: "#fff",
                alignItems: "center",
                flex: 1.0,
                justifyContent: "center"
              },
              children: React.createElement(ReactNative.Button, {
                    onPress: (function (param) {
                        Auth.signOut(Service.auth);
                        
                      }),
                    title: "sign out"
                  })
            });
}

var make = HomeScreen;

export {
  make ,
  
}
/* react Not a pure module */
