// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNativePaper from "../bindings/ReactNativePaper.bs.js";

function Header(Props) {
  return React.createElement(ReactNativePaper.Appbar.Header.make, {
              children: React.createElement(ReactNativePaper.Appbar.Content.make, {
                    title: "Hello"
                  })
            });
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
