// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Provider from "./Provider.bs.js";
import * as Navigation from "./Navigation.bs.js";
import * as ExpoWebBrowser from "expo-web-browser";

ExpoWebBrowser.maybeCompleteAuthSession();

function App(Props) {
  return React.createElement(Provider.make, {
              children: React.createElement(Navigation.Root.make, {})
            });
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
