// Generated by ReScript, PLEASE EDIT WITH CARE


var firebase = {
  apiKey: "AIzaSyBPP1iJxgdezIEHB9R6PKADjnLBRcwYXaA",
  authDomain: "lavie-9636a.firebaseapp.com",
  projectId: "lavie-9636a",
  storageBucket: "lavie-9636a.appspot.com",
  messagingSenderId: "673280897807",
  appId: "1:673280897807:web:69c0aa833917e42ae4847a",
  measurementId: "G-6HFEE6LKE0"
};

var googleWebClientId = "673280897807-uns6eud7itjfhpfm1j3rrucnou71tqgb.apps.googleusercontent.com";

export {
  firebase ,
  googleWebClientId ,
  
}
/* No side effect */
