// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.bs.js";
import * as App from "firebase/app";
import * as Auth from "firebase/auth";

var app = App.initializeApp(Config.firebase);

var auth = Auth.getAuth(app);

export {
  app ,
  auth ,
  
}
/* app Not a pure module */
